name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Action to perform'
        type: choice
        options:
          - Build only
          - Build & Release
        default: 'Build only'

jobs:
  build:
    uses: Reaching-Random/gh-actions/.github/workflows/minecraft-build.yml@main
    with:
      minecraft_version: '26.1'
      java_version: '25'
      create_release: ${{ inputs.build_type == 'Build & Release' }}
      modrinth_version_type: release
    permissions:
      contents: write
    secrets:
      gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
